version: '3.8'
services:
  broad-listening:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/scatter/next-app/node_modules
    working_dir: /app
    environment:
      - FLASK_APP=web.app
    stdin_open: true
    tty: true